<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKR4oJc9\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKR4oJc9/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKR4oJc9.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKR4oJc9\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKR4oJc9\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KR4oJc9',
    'container.build_id' => '7bd7779d',
    'container.build_time' => 1578233788,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKR4oJc9');
